//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketTrace.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TicketMain
    {
        public int TID { get; set; }
        public Nullable<int> FID { get; set; }
        public Nullable<int> UID { get; set; }
        [Required]
        public string Summary { get; set; }
        [Required]
        public string Description { get; set; }
        public Nullable<bool> Severity { get; set; }
        public Nullable<bool> Priority { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> Resolve { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
